name: Build And Deploy To Tencent ECS

on:                               
  push:
    branches: [ "master" ]

jobs:                             
  build-and-deploy:
    runs-on: ubuntu-latest        
    steps:                        
    - uses: actions/checkout@v3


    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x' 

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Build site
      run: npm build

    - name: Deploy to tencent server        
      uses: easingthemes/ssh-deploy@v3.0.0      
      env:
        SSH_PRIVATE_KEY: ${{ secrets.BLOG_SSHKEY }} 
        ARGS: "-avzr --delete"
        SOURCE: "blog/.vuepress/dist/*"
        REMOTE_HOST: ${{ secrets.BLOG_HOST }}
        REMOTE_USER: ${{ secrets.BLOG_USER }}
        TARGET: "/var/www/html/"